<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <IsPackable>true</IsPackable>
    <PackageId>Nubbin</PackageId>
    <Version>0.5.0</Version> <!-- x-release-please-version -->
    <Authors>Steven Vermeeren</Authors>
    <Description>A C# source generator for creating dummy implementations of abstract and interface members.</Description>
    <PackageTags>source-generator;roslyn;stubs;testing;mocking</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Nubbin.Test" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp"
                      Version="4.14.0"
                      PrivateAssets="all" />
    <None Include="../README.md" Pack="true" PackagePath="README.md" />
    <None Include="../LICENSE" Pack="true" PackagePath="LICENSE" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>

</Project>
