using System.Text;
using Microsoft.CodeAnalysis;

namespace Nubbin.Generator;

internal static class StubSourceEmitter
{
    public static void Emit(SourceProductionContext context, INamedTypeSymbol type)
    {
        var methods = StubMemberDiscovery.FindMissingMethods(type).ToArray();
        var properties = StubMemberDiscovery.FindMissingProperties(type).ToArray();
        if (methods.Length == 0 && properties.Length == 0)
        {
            return;
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.Append("namespace ").Append(type.ContainingNamespace.ToDisplayString()).AppendLine(";");
        source.AppendLine();
        source.Append(SymbolFormatting.GetTypeAccessibility(type)).Append(" partial class ").Append(type.Name).AppendLine();
        source.AppendLine("{");

        foreach (var method in methods)
        {
            AppendMethod(source, method);
        }

        foreach (var property in properties)
        {
            AppendProperty(source, property);
        }

        if (properties.Length > 0)
        {
            AppendPropertyAccessor(source, properties);
        }

        source.AppendLine("}");
        context.AddSource(type.Name + ".Stub.g.cs", source.ToString());
    }

    private static void AppendMethod(StringBuilder source, IMethodSymbol method)
    {
        source.Append("    ").Append(SymbolFormatting.GetMethodDeclaration(method)).AppendLine();
        source.AppendLine("    {");
        foreach (var parameter in method.Parameters.Where(parameter => parameter.RefKind == RefKind.Out))
        {
            source.Append("        ").Append(parameter.Name).AppendLine(" = default!;");
        }

        if (StubDefaults.IsTask(method.ReturnType, out var taskResultType))
        {
            if (taskResultType is null)
            {
                source.AppendLine("        return global::System.Threading.Tasks.Task.CompletedTask;");
            }
            else
            {
                source.Append("        return global::System.Threading.Tasks.Task.FromResult<")
                    .Append(taskResultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                    .Append(">(")
                    .Append(StubDefaults.GetReturnExpression(taskResultType))
                    .AppendLine(");");
            }
        }
        else if (!method.ReturnsVoid)
        {
            source.Append("        return ").Append(StubDefaults.GetReturnExpression(method.ReturnType)).AppendLine(";");
        }

        source.AppendLine("    }");
    }

    private static void AppendProperty(StringBuilder source, IPropertySymbol property)
    {
        source.Append("    ").Append(SymbolFormatting.GetPropertyDeclaration(property)).AppendLine();
        source.AppendLine("    {");
        if (SymbolFormatting.HasGetter(property))
        {
            source.Append("        get => Properties.").Append(property.Name).AppendLine(";");
        }
        if (SymbolFormatting.HasSetter(property))
        {
            source.Append("        set => Properties.").Append(property.Name).AppendLine(" = value;");
        }
        source.AppendLine("    }");
    }

    private static void AppendPropertyAccessor(StringBuilder source, IReadOnlyCollection<IPropertySymbol> properties)
    {
        source.AppendLine("    public PropertyAccessor Properties { get; } = new PropertyAccessor();");
        source.AppendLine("    public class PropertyAccessor");
        source.AppendLine("    {");
        foreach (var property in properties)
        {
            source.Append("        public ")
                .Append(property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .Append(' ').Append(property.Name).Append(" { get; set; } = ")
                .Append(StubDefaults.GetReturnExpression(property.Type)).AppendLine(";");
        }
        source.AppendLine("    }");
    }
}