using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Nubbin.Generator;

/// <summary>
/// Generates dummy implementations for classes marked with <see cref="StubAttribute"/>.
/// </summary>
[Generator]
public sealed class StubGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Registers the incremental pipeline that discovers <see cref="StubAttribute"/> targets.
    /// </summary>
    /// <param name="context">The generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targets = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Nubbin.StubAttribute",
            static (node, _) => node is ClassDeclarationSyntax,
            static (syntaxContext, _) =>
                ((INamedTypeSymbol)syntaxContext.TargetSymbol, (ClassDeclarationSyntax)syntaxContext.TargetNode));

        context.RegisterSourceOutput(targets, static (productionContext, target) =>
        {
            Emit(productionContext, target.Item1, target.Item2);
        });
    }

    private static void Emit(SourceProductionContext context, INamedTypeSymbol type, ClassDeclarationSyntax declaration)
    {
        var methods = FindMissingMethods(type).ToArray();
        if (methods.Length == 0)
        {
            return;
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.Append("namespace ").Append(type.ContainingNamespace.ToDisplayString()).AppendLine(";");
        source.AppendLine();
        source.Append(GetAccessibility(type)).Append(" partial class ").Append(type.Name).AppendLine();
        source.AppendLine("{");

        foreach (var method in methods)
        {
            source.Append("    ").Append(GetMethodDeclaration(method)).AppendLine();
            source.AppendLine("    {");
            foreach (var parameter in method.Parameters.Where(parameter => parameter.RefKind == RefKind.Out))
            {
                source.Append("        ").Append(parameter.Name).AppendLine(" = default!;");
            }
            if (IsTask(method.ReturnType, out var taskResultType))
            {
                if (taskResultType is null)
                {
                    source.AppendLine("        return global::System.Threading.Tasks.Task.CompletedTask;");
                }
                else
                {
                    source.Append("        return global::System.Threading.Tasks.Task.FromResult<")
                        .Append(taskResultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                        .Append(">(")
                        .Append(GetReturnExpression(taskResultType))
                        .AppendLine(");");
                }
            }
            else if (!method.ReturnsVoid)
            {
                source.Append("        return ").Append(GetReturnExpression(method.ReturnType)).AppendLine(";");
            }
            source.AppendLine("    }");
        }

        source.AppendLine("}");
        context.AddSource(type.Name + ".Stub.g.cs", source.ToString());
    }

    private static IEnumerable<IMethodSymbol> FindMissingMethods(INamedTypeSymbol type)
    {
        var candidates = new List<IMethodSymbol>();

        for (var baseType = type.BaseType; baseType is not null; baseType = baseType.BaseType)
        {
            candidates.AddRange(baseType.GetMembers().OfType<IMethodSymbol>().Where(method => method.IsAbstract));
        }

        foreach (var interfaceType in type.AllInterfaces)
        {
            candidates.AddRange(interfaceType.GetMembers().OfType<IMethodSymbol>().Where(method => method.IsAbstract));
        }

        var emitted = new HashSet<string>(StringComparer.Ordinal);
        foreach (var candidate in candidates)
        {
            var key = GetMethodKey(candidate);
            if (!emitted.Add(key) || HasConcreteImplementation(type, candidate))
            {
                continue;
            }

            yield return candidate;
        }
    }

    private static bool HasConcreteImplementation(INamedTypeSymbol type, IMethodSymbol candidate)
    {
        if (candidate.ContainingType.TypeKind == TypeKind.Interface)
        {
            var implementation = type.FindImplementationForInterfaceMember(candidate);
            return implementation is not null && !implementation.IsAbstract;
        }

        for (var current = type; current is not null; current = current.BaseType)
        {
            var method = current.GetMembers(candidate.Name).OfType<IMethodSymbol>()
                .FirstOrDefault(item => HasSameSignature(item, candidate));
            if (method is not null)
            {
                return !method.IsAbstract;
            }
        }

        return false;
    }

    private static bool HasSameSignature(IMethodSymbol left, IMethodSymbol right)
    {
        return left.Arity == right.Arity &&
            left.Parameters.Length == right.Parameters.Length &&
            left.Parameters.Zip(right.Parameters, (leftParameter, rightParameter) =>
                leftParameter.RefKind == rightParameter.RefKind &&
                SymbolEqualityComparer.Default.Equals(leftParameter.Type, rightParameter.Type)).All(result => result);
    }

    private static string GetMethodKey(IMethodSymbol method)
    {
        return method.Name + method.Arity + ":" + string.Join(",", method.Parameters.Select(parameter =>
            parameter.RefKind + ":" + parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
    }

    private static bool IsTask(ITypeSymbol returnType, out ITypeSymbol? resultType)
    {
        if (returnType is INamedTypeSymbol namedType &&
            namedType.ContainingNamespace.ToDisplayString() == "System.Threading.Tasks" &&
            namedType.Name == "Task")
        {
            resultType = namedType.TypeArguments.Length == 1 ? namedType.TypeArguments[0] : null;
            return true;
        }

        resultType = null;
        return false;
    }

    private static string GetReturnExpression(ITypeSymbol returnType)
    {
        if (returnType is INamedTypeSymbol namedType &&
            namedType.TypeKind == TypeKind.Class &&
            !namedType.IsAbstract &&
            namedType.InstanceConstructors.Any(constructor =>
                constructor.DeclaredAccessibility == Accessibility.Public &&
                constructor.Parameters.Length == 0))
        {
            var typeName = returnType.WithNullableAnnotation(NullableAnnotation.NotAnnotated)
                .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return "new " + typeName + "()";
        }

        return "default!";
    }

    private static string GetMethodDeclaration(IMethodSymbol method)
    {
        var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var parameters = string.Join(", ", method.Parameters.Select(parameter =>
            (parameter.IsParams ? "params " : string.Empty) +
            (parameter.RefKind switch
            {
                RefKind.Ref => "ref ",
                RefKind.Out => "out ",
                RefKind.In => "in ",
                _ => string.Empty
            }) + parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + " " + parameter.Name));
        var typeParameters = method.Arity == 0 ? string.Empty : "<" + string.Join(", ", method.TypeParameters.Select(parameter => parameter.Name)) + ">";
        var overrideModifier = method.ContainingType.TypeKind == TypeKind.Interface ? string.Empty : "override ";

        var accessibility = method.ContainingType.TypeKind == TypeKind.Interface
            ? "public"
            : GetMethodAccessibility(method);

        return accessibility + " " + overrideModifier + returnType + " " + method.Name + typeParameters + "(" + parameters + ")";
    }

    private static string GetMethodAccessibility(IMethodSymbol method)
    {
        return method.DeclaredAccessibility switch
        {
            Accessibility.Protected => "protected",
            Accessibility.Internal => "internal",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            _ => "public"
        };
    }

    private static string GetAccessibility(INamedTypeSymbol type)
    {
        return type.DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            _ => string.Empty
        };
    }
}