using System.Text;
using Microsoft.CodeAnalysis;

namespace Nubbin.Generator;

internal static class StubSourceEmitter
{
    public static void Emit(SourceProductionContext context, INamedTypeSymbol type)
    {
        var methods = StubMemberDiscovery.FindMissingMethods(type).ToArray();
        var properties = StubMemberDiscovery.FindMissingProperties(type).ToArray();
        var storageProperties = properties.Where(SymbolFormatting.RequiresPropertyStorage).ToArray();
        if (methods.Length == 0 && properties.Length == 0)
        {
            return;
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.Append("namespace ").Append(type.ContainingNamespace.ToDisplayString()).AppendLine();
        source.AppendLine("{");
        source.Append("    ").Append(SymbolFormatting.GetTypeAccessibility(type)).Append(" partial class ").Append(type.Name).AppendLine();
        source.AppendLine("    {");

        foreach (var method in methods)
        {
            AppendMethod(source, method);
        }

        foreach (var property in properties)
        {
            AppendProperty(source, type, property, storageProperties.Contains(property, SymbolEqualityComparer.Default));
        }

        source.AppendLine("    }");
        if (storageProperties.Length > 0)
        {
            source.AppendLine("}");
            AppendPropertyStorage(source, type, storageProperties);
        }
        else
        {
            source.AppendLine("}");
        }

        context.AddSource(type.Name + ".Stub.g.cs", source.ToString());
    }

    private static void AppendMethod(StringBuilder source, IMethodSymbol method)
    {
        source.Append("        ").Append(SymbolFormatting.GetMethodDeclaration(method)).AppendLine();
        source.AppendLine("        {");
        foreach (var parameter in method.Parameters.Where(parameter => parameter.RefKind == RefKind.Out))
        {
            source.Append("            ").Append(parameter.Name).AppendLine(" = default!;");
        }

        if (StubDefaults.IsTask(method.ReturnType, out var taskResultType))
        {
            if (taskResultType is null)
            {
                source.AppendLine("            return global::System.Threading.Tasks.Task.CompletedTask;");
            }
            else
            {
                source.Append("            return global::System.Threading.Tasks.Task.FromResult<")
                    .Append(taskResultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                    .Append(">(")
                    .Append(StubDefaults.GetReturnExpression(taskResultType))
                    .AppendLine(");");
            }
        }
        else if (!method.ReturnsVoid)
        {
            source.Append("            return ").Append(StubDefaults.GetReturnExpression(method.ReturnType)).AppendLine(";");
        }

        source.AppendLine("        }");
    }

    private static void AppendProperty(
        StringBuilder source,
        INamedTypeSymbol type,
        IPropertySymbol property,
        bool useStorage)
    {
        source.Append("        ").Append(SymbolFormatting.GetPropertyDeclaration(property));
        if (!useStorage)
        {
            source.Append(" { get; set; } = ").Append(StubDefaults.GetReturnExpression(property.Type)).AppendLine(";");
            return;
        }

        source.AppendLine();
        source.AppendLine("        {");
        if (SymbolFormatting.HasGetter(property))
        {
            source.Append("            get => global::Nubbin.Stubs")
                .Append(".GetPropertyHelper(this).").Append(property.Name).AppendLine(";");
        }
        if (SymbolFormatting.HasSetter(property))
        {
            source.Append("            set => global::Nubbin.Stubs")
                .Append(".GetPropertyHelper(this).").Append(property.Name).AppendLine(" = value;");
        }
        source.AppendLine("        }");
    }

    private static void AppendPropertyStorage(
        StringBuilder source,
        INamedTypeSymbol type,
        IReadOnlyCollection<IPropertySymbol> properties)
    {
        var typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var propertiesTypeName = GetPropertyStorageTypeName(type);
        var qualifiedPropertiesTypeName = GetQualifiedPropertyStorageTypeName(type);
        var accessibility = SymbolFormatting.GetGeneratedTypeAccessibility(type);

        source.AppendLine("namespace Nubbin");
        source.AppendLine("{");
        source.Append("    ").Append(accessibility).Append(" static partial class Stubs").AppendLine();
        source.AppendLine("    {");
        source.Append("        ").Append(accessibility).Append(" static ").Append(qualifiedPropertiesTypeName)
            .Append(" GetPropertyHelper(this ").Append(typeName).AppendLine(" owner)");
        source.Append("            => global::Nubbin.StubPropertyStorage<").Append(typeName).Append(", ")
            .Append(qualifiedPropertiesTypeName).AppendLine(">.Get(owner);");
        source.AppendLine("    }");
        source.AppendLine("}");
        source.Append("namespace ").Append(GetPropertyHelperNamespace(type)).AppendLine();
        source.AppendLine("{");
        source.Append("    ").Append(accessibility).Append(" sealed class ").AppendLine(propertiesTypeName);
        source.AppendLine("    {");
        foreach (var property in properties)
        {
            source.Append("        public ")
                .Append(property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .Append(' ').Append(property.Name).Append(" { get; set; } = ")
                .Append(StubDefaults.GetReturnExpression(property.Type)).AppendLine(";");
        }
        source.AppendLine("    }");
        source.AppendLine("}");
    }

    private static string GetPropertyExtensionsTypeName(INamedTypeSymbol type)
    {
        return "Stubs";
    }

    private static string GetPropertyStorageTypeName(INamedTypeSymbol type)
    {
        return type.Name + "PropertyHelper";
    }

    private static string GetQualifiedPropertyStorageTypeName(INamedTypeSymbol type)
    {
        return "global::" + GetPropertyHelperNamespace(type) + "." + GetPropertyStorageTypeName(type);
    }

    private static string GetPropertyHelperNamespace(INamedTypeSymbol type)
    {
        var namespaceName = type.ContainingNamespace.ToDisplayString();
        return string.IsNullOrEmpty(namespaceName) ? "Nubbin" : namespaceName + ".Nubbin";
    }
}