using System.Text;

namespace Nubbin.Generator.Emitting;

internal class IndentedStringBuilder
{
    private readonly StringBuilder _builder = new();
    private bool _isNewLine = true;
    private int _indent = 0;

    public IndentedStringBuilder()
    { 
        _builder.AppendLine("// <auto-generated />");
        AppendLine("#nullable enable");
    }

    public IndentedStringBuilder Append(string value)
    {
        WithIndent(_builder).Append(value);
        return this;
    }

    public IndentedStringBuilder AppendLine(string value)
    {
        WithIndent(_builder).AppendLine(value);
        _isNewLine = true;
        return this;
    }

    public IndentedStringBuilder AppendLine()
    {
        WithIndent(_builder).AppendLine();
        _isNewLine = true;
        return this;
    }

    public IndentedStringBuilder Indent()
    {
        _indent++;
        return this;
    }

    public IndentedStringBuilder Pop()
    {
        _indent--;
        return this;
    }

    private StringBuilder WithIndent(StringBuilder source)
    {
        if (_isNewLine)
        {
            for (var i = 0; i < _indent; i++)
            {
                source.Append("    ");
            }
        }

        _isNewLine = false;
        return source;
    }

    public override string ToString()
    {
        return _builder.ToString();
    }
}