using Nubbin.Generator.Emitting;

namespace Nubbin.Test.Generator.Emitting;

public class IndentedStringBuilderTests
{
    [Fact]
    public void AppendsLinesWithIndentationTracking()
    {
        var builder = new IndentedStringBuilder();

        builder.AppendLine("public class Sample");
        builder.Indent();
        builder.AppendLine("public int Value { get; set; }");
        builder.Pop();
        builder.AppendLine("}");

        var result = builder.ToString();

        Assert.Contains("public class Sample", result);
        Assert.Contains("    public int Value { get; set; }", result);
        Assert.Contains("}", result);
    }

    [Fact]
    public void MaintainsAutoGeneratedHeaderForEachBuilder()
    {
        var builder = new IndentedStringBuilder();

        Assert.StartsWith("// <auto-generated />", builder.ToString());
    }
}
